# Generated by Django 3.0.7 on 2020-06-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_remove_user_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Task.Task'),
        ),
    ]
