# Generated by Django 3.0.7 on 2020-06-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_auto_20200607_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='currentlyWorking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='totaltime',
            field=models.FloatField(default=0.0),
        ),
    ]
