# Generated by Django 3.0.7 on 2020-06-16 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0007_auto_20200607_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='totaltime',
        ),
        migrations.AddField(
            model_name='task',
            name='startedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
