# Generated by Django 3.0.7 on 2020-06-16 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_auto_20200615_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='totaltime',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
