# Generated by Django 3.0.7 on 2020-07-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0009_task_totaltime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('userReference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Task.User')),
            ],
        ),
    ]
