# Generated by Django 3.0.7 on 2020-07-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0010_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='userReference',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.User'),
        ),
    ]
