# Generated by Django 3.0.7 on 2020-07-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0011_auto_20200702_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='userReference',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Task.User'),
        ),
    ]
