# Generated by Django 3.0.7 on 2020-07-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0012_auto_20200702_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='TrainImage',
        ),
    ]
